apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: santanarael/order-fiap
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: root
            - name: DB_NAME
              value: postech
            - name: CLIENT_URL
              value: http://custumer-service:32323
            - name: PAYMENT_URL
              value: http://payment-service:34343
            - name: AMQP_USER
              value: guest
            - name: AMQP_PASS
              value: guest
            - name: AMQP_HOST
              value: http://a828ed4fc239c47ae9e5d106ff020fac-1949601428.us-east-1.elb.amazonaws.com
            - name: AMQP_PORT
              value: '5672'
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '628Mi'
              cpu: '300m'
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 33333
      targetPort: 3000
  type: LoadBalancer
